version: '3'

services:
  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
    environment:
      - KAKAO_ID=${KAKAO_ID}
      - KAKAO_SECRET_ID=${KAKAO_SECRET_ID}
      - LOGIN_REDIRECT_URI=${LOGIN_REDIRECT_URI}
      - NAVER_ID=${NAVER_ID}
      - NAVER_SECRET_ID=${NAVER_SECRET_ID}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - OPEN_AI_KEY=${OPEN_AI_KEY}